### ISSUE TITLE
Import users script

### ISSUE THREAD

**Issue by 50Fifty** [50Fifty/auth-scheduled-backup#43]

**Comment by gregfenton** [comment]
Do you have even a bullet-point idea of how to approach this?
Is it purely using Admin SDK APIs, or do you foresee needing to massage the data in some way?

**Comment by 50Fifty** [comment]
@gregfenton The users can be imported via the [Admin SDK](https://firebase.google.com/docs/auth/admin/import-users). There isn't a need to do any kind of data manipulation for it.

**Comment by gregfenton** [comment]
What about handling of the hashed passwords?  How does that work?  What parameters would I need to specify in order to import the password hashes correctly to the new location?

**Comment by gregfenton** [comment]
Excellent! So we've already begun the work for this issue! 😄

**Comment by 50Fifty** [comment]
Import script is available in a [separate repo](https://github.com/50Fifty/auth-scheduled-backup-import)
